import { create } from "zustand"
import { persist } from "zustand/middleware"

export type Role = "SUPER_ADMIN" | "ADMIN" | "USER"
export type ItemCategory = "Weapon" | "Case" | "Sticker" | "Gloves" | "Knife" | "Charm" | "Silah" | "Kasa" | "Etiket" | "Eldiven"
export type Category = ItemCategory
export type UserStatus = "ACTIVE" | "BANNED"
export interface InventoryItem { id: string; name: string; image: string; purchasedAt: number; price: number; category: ItemCategory }
export interface User { id: string; email: string; username: string; displayName: string; avatar: string | null; photoURL: string | null; banner: string | null; bio: string; steamTradeUrl: string; role: Role; status: UserStatus; points: number; jtorePoints: number; inventory: InventoryItem[]; createdAt: number; lastSeen: number; provider: "email" | "steam" }
export interface StoreItem { id: string; name: string; category: ItemCategory; image: string; price: number; stock: number; active: boolean; createdAt: number }
export interface Tournament { id: string; name: string; date: string; prize: string; maxSlots?: number; bracketType?: "Single Elimination" | "Double Elimination" | "Swiss"; status: "UPCOMING" | "LIVE" | "ENDED"; registrationOpen: boolean; createdAt: number }
export interface Announcement { id: string; title: string; body: string; active: boolean; createdAt: number }
export interface AuditLog { id: string; action: string; actor: string; target: string; detail: string; createdAt: number }
export interface QuizConfig { question: string; options: string[]; correctIndex: number; reward: number; active: boolean }
export interface AdsConfig { masterEnabled: boolean; leaderboard: boolean; sidebar: boolean; inFeed: boolean; sticky: boolean }
export type Rarity = "Mil-Spec" | "Restricted" | "Classified" | "Covert"
export interface PlatformConfig { categories: string[]; flashSale: boolean; customCss: string; matchTicker: string; dailyVisitors: number }
export interface Campaign { id: string; title: string; description: string; reward: number; templateId: string; active: boolean; createdAt: number }


export const ADMIN_EMAIL = "oyunbulucu300@gmail.com"
const today = () => new Date().toISOString().slice(0, 10)
const empty = { campaigns: [] as Campaign[], totalPointsDistributed: 0, users: [] as User[], storeItems: [] as StoreItem[], tournaments: [] as Tournament[], announcements: [] as Announcement[], audits: [] as AuditLog[], currentUser: null as User | null, completedTasks: {} as Record<string, string[]>, maintenanceMode: false, platform: { categories: ["Weapon", "Case", "Sticker", "Gloves", "Knife", "Charm"], flashSale: false, customCss: "", matchTicker: "JTORE 0 : 0 LIVE", dailyVisitors: 128 } as PlatformConfig, quiz: { question: "What is the maximum competitive round time in CS2?", options: ["1:55", "2:00", "2:15", "2:30"], correctIndex: 1, reward: 15, active: true } as QuizConfig, ads: { masterEnabled: true, leaderboard: true, sidebar: true, inFeed: true, sticky: true } as AdsConfig }

interface AppState { campaigns: Campaign[]; totalPointsDistributed: number; users: User[]; storeItems: StoreItem[]; tournaments: Tournament[]; announcements: Announcement[]; audits: AuditLog[]; currentUser: User | null; completedTasks: Record<string, string[]>; maintenanceMode: boolean; platform: PlatformConfig; quiz: QuizConfig; ads: AdsConfig; login: (email: string, provider?: User["provider"], profile?: Partial<User>) => User; logout: () => void; updateProfile: (patch: Partial<Pick<User, "username" | "displayName" | "avatar" | "banner" | "bio" | "steamTradeUrl">>) => void; purchaseItem: (id: string) => { ok: boolean; message: string }; completeDailyTask: (points: number) => { ok: boolean; message: string }; isDailyTaskDone: () => boolean; addPoints: (userId: string, amount: number, reason: string) => void; addItem: (item: Omit<StoreItem, "id" | "createdAt" | "active">) => void; updateStock: (id: string, stock: number) => void; deleteItem: (id: string) => void; purchase: (id: string) => { ok: boolean; message: string }; completeTask: (taskId: string) => void; updateQuiz: (quiz: QuizConfig) => void; updateAds: (patch: Partial<AdsConfig>) => void; updatePlatform: (patch: Partial<PlatformConfig>) => void; updateItem: (id: string, patch: Partial<StoreItem>) => void; createCampaign: (campaign: Omit<Campaign, "id" | "createdAt" | "active">) => void; toggleCampaign: (id: string) => void; completeCampaign: (id: string, reward: number) => { ok: boolean; message: string }; toggleMaintenance: () => void; upsertAnnouncement: (a: Omit<Announcement, "id" | "createdAt"> & { id?: string }) => void; deleteAnnouncement: (id: string) => void; addTournament: (t: Omit<Tournament, "id" | "createdAt">) => void; updateTournament: (id: string, patch: Partial<Omit<Tournament, "id" | "createdAt">>) => void; deleteTournament: (id: string) => void; toggleRegistration: (id: string) => void; updateUser: (id: string, patch: Partial<Pick<User, "role" | "status">>) => void }

const createUser = (email: string, provider: User["provider"], profile: Partial<User> = {}): User => ({ id: profile.id || `usr_${Date.now()}`, email: email.toLowerCase(), username: profile.username || email.split("@")[0], displayName: profile.displayName || email.split("@")[0], avatar: profile.avatar || null, banner: profile.banner || null, bio: profile.bio || "", steamTradeUrl: profile.steamTradeUrl || "", role: email.toLowerCase() === ADMIN_EMAIL ? "SUPER_ADMIN" : "USER", status: "ACTIVE", points: 0, jtorePoints: 0, photoURL: profile.photoURL || profile.avatar || null, inventory: [], createdAt: Date.now(), lastSeen: Date.now(), provider })

export const useStore = create<AppState>()(persist((set, get) => ({ ...empty,
  login: (email, provider = "email", profile = {}) => { const existing = get().users.find(u => u.email === email.toLowerCase()); const user = existing ? { ...existing, ...profile, photoURL: profile.photoURL ?? profile.avatar ?? existing.photoURL, jtorePoints: profile.jtorePoints ?? existing.jtorePoints ?? existing.points, points: profile.points ?? profile.jtorePoints ?? existing.points, role: email.toLowerCase() === ADMIN_EMAIL ? "SUPER_ADMIN" as Role : existing.role, lastSeen: Date.now(), provider } : createUser(email, provider, profile); set(s => ({ users: existing ? s.users.map(u => u.id === user.id ? user : u) : [...s.users, user], currentUser: user })); return user },
  logout: () => set({ currentUser: null }),
  updateProfile: patch => set(s => { if (!s.currentUser) return s; const user = { ...s.currentUser, ...patch, photoURL: patch.avatar ?? s.currentUser.photoURL }; return { currentUser: user, users: s.users.map(u => u.id === user.id ? user : u) } }),
  purchaseItem: id => get().purchase(id),
  completeDailyTask: points => { const s = get(); if (!s.currentUser) return { ok: false, message: "Sign in required" }; const key = `${today()}:${s.currentUser.id}`; if ((s.completedTasks[key] || []).includes("daily-quiz")) return { ok: false, message: "Today's task is already complete" }; const user = { ...s.currentUser, points: s.currentUser.points + points, jtorePoints: s.currentUser.points + points }; set(st => ({ totalPointsDistributed: st.totalPointsDistributed + points, currentUser: user, users: st.users.map(u => u.id === user.id ? user : u), completedTasks: { ...st.completedTasks, [key]: [...(st.completedTasks[key] || []), "daily-quiz"] } })); return { ok: true, message: `+${points} Points earned!` } },
  isDailyTaskDone: () => { const s = get(); return !!s.currentUser && (s.completedTasks[`${today()}:${s.currentUser.id}`] || []).includes("daily-quiz") },
  addPoints: (userId, amount, reason) => set(s => { const target = s.users.find(u => u.id === userId); if (!target) return s; const user = { ...target, points: target.points + amount }; return { totalPointsDistributed: s.totalPointsDistributed + Math.max(0, amount), users: s.users.map(u => u.id === userId ? user : u), currentUser: s.currentUser?.id === userId ? user : s.currentUser, audits: [{ id: `audit_${Date.now()}`, action: "POINTS_INJECTION", actor: s.currentUser?.email || "system", target: target.email, detail: `${amount} points: ${reason}`, createdAt: Date.now() }, ...s.audits] } }),
  addItem: item => set(s => ({ storeItems: [{ ...item, id: `item_${Date.now()}`, active: true, createdAt: Date.now() }, ...s.storeItems] })), updateStock: (id, stock) => set(s => ({ storeItems: s.storeItems.map(i => i.id === id ? { ...i, stock: Math.max(0, stock) } : i) })), deleteItem: id => set(s => ({ storeItems: s.storeItems.filter(i => i.id !== id) })),
  purchase: id => { const s = get(); if (!s.currentUser) return { ok: false, message: "Please sign in first." }; const item = s.storeItems.find(i => i.id === id); if (!item) return { ok: false, message: "Item not found." }; if (item.stock < 1) return { ok: false, message: "This item is sold out." }; if (s.currentUser.points < item.price) return { ok: false, message: "Not enough JTORE Points." }; const user = { ...s.currentUser, points: s.currentUser.points - item.price, jtorePoints: s.currentUser.points - item.price, inventory: [{ id: `inv_${Date.now()}`, name: item.name, image: item.image, category: item.category, purchasedAt: Date.now(), price: item.price }, ...s.currentUser.inventory] }; set({ currentUser: user, users: s.users.map(u => u.id === user.id ? user : u), storeItems: s.storeItems.map(i => i.id === id ? { ...i, stock: i.stock - 1 } : i), audits: [{ id: `audit_${Date.now()}`, action: "PURCHASE", actor: user.email, target: item.name, detail: `${item.price} points`, createdAt: Date.now() }, ...s.audits] }); return { ok: true, message: `${item.name} added to your inventory.` } },
  completeTask: taskId => set(s => { const key = `${today()}:${s.currentUser?.id || "guest"}`; return { completedTasks: { ...s.completedTasks, [key]: [...new Set([...(s.completedTasks[key] || []), taskId])] } } }), updateQuiz: quiz => set({ quiz }), updateAds: patch => set(s => ({ ads: { ...s.ads, ...patch } })), updatePlatform: patch => set(s => ({ platform: { ...s.platform, ...patch } })), updateItem: (id, patch) => set(s => ({ storeItems: s.storeItems.map(item => item.id === id ? { ...item, ...patch } : item) })), createCampaign: campaign => set(s => ({ campaigns: [{ ...campaign, id: `campaign_${Date.now()}`, active: false, createdAt: Date.now() }, ...s.campaigns] })), toggleCampaign: id => set(s => ({ campaigns: s.campaigns.map(c => c.id === id ? { ...c, active: !c.active } : c) })), completeCampaign: (id, reward) => { const s = get(); if (!s.currentUser) return { ok: false, message: "Sign in required" }; const campaign = s.campaigns.find(c => c.id === id); if (!campaign || !campaign.active) return { ok: false, message: "Campaign unavailable" }; const key = `${today()}:${s.currentUser.id}`; if ((s.completedTasks[key] || []).includes(id)) return { ok: false, message: "Campaign already completed" }; const user = { ...s.currentUser, points: s.currentUser.points + reward, jtorePoints: s.currentUser.points + reward }; set({ totalPointsDistributed: s.totalPointsDistributed + reward, currentUser: user, users: s.users.map(u => u.id === user.id ? user : u), completedTasks: { ...s.completedTasks, [key]: [...(s.completedTasks[key] || []), id] } }); return { ok: true, message: `+${reward} Points earned!` } }, toggleMaintenance: () => set(s => ({ maintenanceMode: !s.maintenanceMode })),
  upsertAnnouncement: a => set(s => ({ announcements: a.id ? s.announcements.map(x => x.id === a.id ? { ...x, ...a } as Announcement : x) : [{ ...a, id: `announcement_${Date.now()}`, createdAt: Date.now() }, ...s.announcements] })), deleteAnnouncement: id => set(s => ({ announcements: s.announcements.filter(a => a.id !== id) })), addTournament: t => set(s => ({ tournaments: [{ ...t, id: `tournament_${Date.now()}`, createdAt: Date.now() }, ...s.tournaments] })), updateTournament: (id, patch) => set(s => ({ tournaments: s.tournaments.map(t => t.id === id ? { ...t, ...patch } : t) })), deleteTournament: id => set(s => ({ tournaments: s.tournaments.filter(t => t.id !== id) })), toggleRegistration: id => set(s => ({ tournaments: s.tournaments.map(t => t.id === id ? { ...t, registrationOpen: !t.registrationOpen } : t) })), updateUser: (id, patch) => set(s => ({ users: s.users.map(u => u.id === id ? { ...u, ...patch } : u), currentUser: s.currentUser?.id === id ? { ...s.currentUser, ...patch } : s.currentUser }))
}), { name: "jtore-db", version: 6, migrate: () => ({ ...empty }), partialize: s => ({ campaigns: s.campaigns, totalPointsDistributed: s.totalPointsDistributed, users: s.users, storeItems: s.storeItems, tournaments: s.tournaments, announcements: s.announcements, audits: s.audits, currentUser: s.currentUser, completedTasks: s.completedTasks, maintenanceMode: s.maintenanceMode, platform: s.platform, quiz: s.quiz, ads: s.ads }) }))

export const isSuperAdmin = (u: User | null) => u?.email.toLowerCase() === ADMIN_EMAIL && u.role === "SUPER_ADMIN"
export const getTaskKey = (id?: string) => `${today()}:${id || "guest"}`
