import { Link, useLocation } from "react-router-dom"
import { Megaphone, ShieldCheck, Menu, X, LogOut, UserRound, Coins } from "lucide-react"
import { useState } from "react"
import { useStore, isSuperAdmin } from "../store/useStore"
import toast from "react-hot-toast"

export function AnnouncementBar() { const announcement = useStore(s => s.announcements.find(a => a.active)); if (!announcement) return null; return <div className="border-b border-orange-500/20 bg-orange-500/10 px-4 py-2 text-center text-sm text-orange-200"><Megaphone className="mr-2 inline h-4 w-4" />{announcement.title}: {announcement.body}</div> }
export function AdSlot({ variant = "leaderboard" }: { variant?: "leaderboard" | "sidebar" | "infeed" | "sticky" }) { const ads = useStore(s => s.ads); const enabled = ads.masterEnabled && ads[variant === "sticky" ? "sticky" : variant]; if (!enabled) return null; return <div className={`ad-slot ${variant === "sidebar" ? "min-h-56" : variant === "infeed" ? "min-h-28" : "min-h-20"}`}><span>{variant === "leaderboard" ? "AdSense Top Banner · 728x90" : variant === "sidebar" ? "AdSense Sidebar · 300x250" : variant === "infeed" ? "AdSense In-Feed · 336x280" : "AdSense Sticky Ad"}</span></div> }
export function Navbar() { const [open, setOpen] = useState(false); const location = useLocation(); const { currentUser, logout } = useStore(); const admin = isSuperAdmin(currentUser); const nav = [["/store","Store"],["/tasks","Tasks"],["/plugins","Plugins"],["/tournaments","Tournaments"]]; return <header className="sticky top-0 z-40 border-b border-white/10 bg-zinc-950/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4"><Link to="/" className="font-display text-xl font-bold tracking-[0.22em] text-white">JTORE<span className="text-orange-500">.</span></Link><nav className="hidden items-center gap-6 md:flex">{nav.map(([href,label]) => <Link key={href} to={href} className={location.pathname === href ? "text-orange-400" : "text-zinc-400 hover:text-white"}>{label}</Link>)}{admin && <Link to="/admin-hq" className="flex items-center gap-1 text-orange-400"><ShieldCheck className="h-4 w-4" />HQ</Link>}</nav><div className="hidden items-center gap-3 md:flex">{currentUser ? <><Link to="/profile" className="flex items-center gap-2 text-sm text-zinc-300">{currentUser.avatar ? <img src={currentUser.avatar} alt="" className="h-8 w-8 rounded-full object-cover" /> : <UserRound className="h-5 w-5" />}<span>{currentUser.username}</span><span className="flex items-center gap-1 text-orange-400"><Coins className="h-4 w-4" />{currentUser.points}</span></Link><button onClick={() => { logout(); toast.success("Signed out") }} className="text-sm text-zinc-500 hover:text-white"><LogOut className="h-4 w-4" /></button></> : <Link to="/auth" className="btn-primary">Sign in</Link>}</div><button className="md:hidden" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div>{open && <div className="border-t border-white/10 bg-zinc-950 px-4 py-4 md:hidden"><div className="flex flex-col gap-4">{nav.map(([href,label]) => <Link key={href} to={href} onClick={() => setOpen(false)}>{label}</Link>)}{admin && <Link to="/admin-hq">Admin HQ</Link>}{currentUser ? <button className="text-left text-zinc-400" onClick={() => { logout(); setOpen(false) }}>Sign out</button> : <Link to="/auth">Sign in</Link>}</div></div>}</header> }
export function Footer() { return <footer className="border-t border-white/10 py-10 text-center text-sm text-zinc-500"><p className="font-display tracking-[0.2em] text-zinc-300">JTORE<span className="text-orange-500">.</span></p><p className="mt-2">The competitive CS2 community platform.</p></footer> }
export function AdsLayout({ children, sidebar = false }: { children: React.ReactNode; sidebar?: boolean }) { return <><AdSlot /><div className={sidebar ? "mx-auto grid max-w-7xl gap-6 px-4 py-8 lg:grid-cols-[1fr_280px]" : "mx-auto max-w-7xl px-4 py-8"}><main>{children}</main>{sidebar && <aside className="hidden lg:block"><AdSlot variant="sidebar" /></aside>}</div><AdSlot variant="sticky" /></> }
export function MaintenanceGate({ children }: { children: React.ReactNode }) { const maintenance = useStore(s => s.maintenanceMode); const currentUser = useStore(s => s.currentUser); if (maintenance && !isSuperAdmin(currentUser)) return <div className="flex min-h-[70vh] items-center justify-center px-4"><div className="glass max-w-lg p-10 text-center"><div className="mb-4 text-5xl">503</div><h1 className="font-display text-3xl font-bold">Platform Maintenance</h1><p className="mt-3 text-zinc-400">JTORE is being upgraded. Please check back soon.</p></div></div>; return <>{children}</> }
export function Layout({ children }: { children: React.ReactNode }) { return <><AnnouncementBar /><Navbar /><MaintenanceGate>{children}</MaintenanceGate><Footer /></> }
